title: Newborn Care Quick Reference
description: Essentials of newborn care in a succinct, interlinked format.
theme: jekyll-theme-dinky

defaults:
  -
    scope:
      path: ""
    values:
      stylesheet: "css/mystyle.css"